---
title: "Lab 00 - Hello IDS!"
author: "Alice Miller"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Alice M", "Alice B", "Anna", 
           "Annie"),
  github_username = c("alicemiller04", "alicebullard", "annascollay", 
                      "anniehodell"), 
  colour = c("indianred", "mistyrose", "maroon", 
             "lightcoral"),
  hobby = c("music", "card games", "card games", 
            "reading"),
  favourite_number = c(10, 8, 6, 4)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```


*Remove this text (including the stars), and add your answer for Exercise 18 here.*

### Exercises 19

Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "username", 
          y = "favourite number",
          title = "best colour palatte")
```

makes graphs

### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby,fill = "indianred")) +
  geom_bar()
p2
```

have coloured bar charts 
